### PR TITLE
[Add page PR] Element attributes and properties

### LINKED ISSUE #4: [Add page] Element properties  - child and content
Include topics like -

1. How to identify by tagname?
2. Types of child - elements, text. Getting children, count, basic navigation through them.
3. Link back to parent
4. Common properties - class, classList, id, direct attributes, get/set/remove any attribute, data attributes, style

### PR DESCRIPTION
**Pull request by bendtherules**
PR for issue - #4. Closes #4 .

Preview link - https://4-element-properties--uiquestions.netlify.app/docs/element-child-content

### CODE REVIEW

**Comment by lakbychance** [comment]
@bendtherules Did some cleanup which I felt was necessary. Also I guess only parentNode is left to mention in this ? Do you have other stuff in mind ?

**Comment by bendtherules** [comment]
I want to add about the basic content stuff - innerText, innerHtml, text nodeValue

**Comment by lakbychance** [comment]
@bendtherules  Oh yup. I don't why I only had only child and parent in mind. 
Definitely those should go in - clear cut differences between the three is good to have.
And I liked the mention of LCRS form :D. Didn't know that.

**Comment by bendtherules** [comment]
Yes, that is helpful if you want to pause and resume traversal, giving back control to something else in meantime (like co-routines/yield).
I think react fibre does something very similar.

**Comment by bendtherules** [comment]
@lapstjup Changes are completed. Please review when free.

Other than the new page, I changed the sidebar a little - made the whole existing section for DOM manipulation, so that individual files don't need to have that in title.

**Comment by lakbychance** [comment]
@bendtherules I have made parentNode as the main section with a related note on parentElement and usage of both in an example. Also , in dom traversal - changed from concat to push, since I believe, earlier our queue was acting like a stack.

**Comment by bendtherules** [comment]
Awesome. I added a little more clarification.

**Comment by bendtherules** [comment]
@lapstjup  If it looks good now, you can approve/merge the request.

**Pull request merged**
